// <auto-generated />
namespace Dota2CharacterCalculator.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddStats : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddStats));
        
        string IMigrationMetadata.Id
        {
            get { return "201612071037558_AddStats"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
